# Generated by Django 4.1.4 on 2023-01-12 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_core', '0003_alter_profile_plan_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='walletaddress',
            name='usdt_address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='walletaddress',
            name='bitcoin_address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='walletaddress',
            name='etherum_address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='walletaddress',
            name='litecoin_address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='walletaddress',
            name='xrp_address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='PendingDeposit',
        ),
    ]
