# Generated by Django 4.1.4 on 2023-01-16 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_core', '0004_walletaddress_usdt_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='walletaddress',
            name='address',
            field=models.CharField(default='Wallet Address', max_length=100),
        ),
    ]
